import { Vehicle } from "./src/types";

const VEHICLES: Vehicle[] = [
    {
        id: "1",
        year: 2020,
        make: "Toyota",
        model: "Camry",
        trim: "SE",
        price: 24999,
        mileage: 35000,
        color: "Silver",
        transmission: "Automatic",
        fuelType: "Gasoline",
        vin: "4T1C11AK5LU123456",
        features: ["Bluetooth", "Backup Camera", "Lane Departure Warning", "Apple CarPlay"],
        condition: "Excellent",
        images: ["/images/toyota.jpg","/images/honda.jpg","/images/toyota.jpg","/images/toyota.jpg","/images/toyota.jpg","/images/toyota.jpg"],
        description: "Well-maintained Camry with one owner. Regular service records available. Clean Carfax report.",
        isFeatured: true,
        isSold: false,
        notes: "One owner, all maintenance records available",
        createdAt: "2024-03-20T00:00:00Z",
        updatedAt: "2024-03-20T00:00:00Z",
        featured: true
    },
    {
        id: "2",
        year: 2014,
        make: "Honda",
        model: "CR-V",
        trim: "EX-L",
        price: 27999,
        mileage: 42000,
        color: "Blue",
        transmission: "Automatic",
        fuelType: "Gasoline",
        vin: "2HKRW2H53KH789012",
        features: ["Leather Seats", "Sunroof", "Honda Sensing", "Android Auto"],
        condition: "Very Good",
        images: ["/images/honda.jpg"],
        description: "Spacious SUV with premium features. All maintenance up to date. Minor wear on driver's seat.",
        isFeatured: false,
        isSold: false,
        notes: "Minor wear on driver's seat",
        createdAt: "2024-03-20T00:00:00Z",
        updatedAt: "2024-03-20T00:00:00Z",
        featured: false
    },
    {
        id: "3",
        year: 2021,
        make: "Ford",
        model: "F-150",
        trim: "XLT",
        price: 42999,
        mileage: 28000,
        color: "Black",
        transmission: "Automatic",
        fuelType: "Gasoline",
        vin: "1FTEW1EG7MFD34567",
        features: ["4x4", "Towing Package", "Sync 4", "Bed Liner"],
        condition: "Excellent",
        images: ["/images/ford.jpg"],
        description: "Powerful V6 engine, perfect for work or recreation. Includes spray-in bedliner and tow package.",
        isFeatured: true,
        isSold: false,
        notes: "Includes spray-in bedliner",
        createdAt: "2024-03-20T00:00:00Z",
        updatedAt: "2024-03-20T00:00:00Z",
        featured: true
    },
    {
        id: "4",
        year: 2018,
        make: "BMW",
        model: "3 Series",
        trim: "M340i",
        price: 31999,
        mileage: 45000,
        color: "White",
        transmission: "Manual",
        fuelType: "Gasoline",
        vin: "WBA8B3G55JNT89012",
        features: ["Sport Package", "Navigation", "Heated Seats", "Parking Sensors"],
        condition: "Very Good",
        images: ["/images/bmw.jpg"],
        description: "Luxury sedan with sport handling. Premium sound system and comfort features included.",
        isFeatured: false,
        isSold: false,
        notes: "Premium sound system included",
        createdAt: "2024-03-20T00:00:00Z",
        updatedAt: "2024-03-20T00:00:00Z",
        featured: true
    },
    {
        id: "5",
        year: 2020,
        make: "Hyundai",
        model: "Tucson",
        trim: "Limited",
        price: 22999,
        mileage: 38000,
        color: "Red",
        transmission: "Automatic",
        fuelType: "Gasoline",
        vin: "KM8J3CA46LU234567",
        features: ["Panoramic Sunroof", "Smart Cruise Control", "Wireless Charging", "Blind Spot Detection"],
        condition: "Excellent",
        images: ["/images/hyundai.jpg"],
        description: "Loaded with features, great fuel economy. Perfect for family use. Clean history.",
        isFeatured: false,
        isSold: false,
        notes: "Clean history, perfect for family use",
        createdAt: "2024-03-20T00:00:00Z",
        updatedAt: "2024-03-20T00:00:00Z",
        featured: false
    },
    {
        id: "6",
        year: 2019,
        make: "Chevrolet",
        model: "Silverado",
        trim: "LT",
        price: 36999,
        mileage: 52000,
        color: "Gray",
        transmission: "Automatic",
        fuelType: "Gasoline",
        vin: "3GCUYEED2KG456789",
        features: ["4x4", "Trailering Package", "Chevy Infotainment", "Bed Cover"],
        condition: "Good",
        images: ["/images/chevy.jpg"],
        description: "Strong V8 engine, great for towing. Includes bed cover and trailering package. Some minor wear on interior.",
        isFeatured: false,
        isSold: false,
        notes: "Some minor wear on interior",
        createdAt: "2024-03-20T00:00:00Z",
        updatedAt: "2024-03-20T00:00:00Z",
        featured: false
    },

];

export default VEHICLES;